### ISSUE TITLE
Perform fuzz test

### ISSUE THREAD

**Issue by avtomat2023** [mike-engel/accept-language-rs#5]
We are going to use your library in our product.
However, we are afraid of panic for invalid input.
It would be very nice if your library was tested by afl.
https://github.com/rust-fuzz/afl.rs

**Comment by mike-engel** [comment]
Hi @yoshrc, thanks for the issue. I'm on holiday right now, but I'll try and take a look after I'm back. This seems like a good idea to me. Thanks!

**Comment by mike-engel** [comment]
Hi @yoshrc, very sorry for the delay, but I've just release 1.2.1 which includes fuzz tests. Over almost 1,000,000 runs, nothing panicked, so I think everything is ok. Thanks for the interest!

**Comment by avtomat2023** [comment]
@mike-engel 
Thank you for your excellent work! We, Future Science Research Inc, will use your crate for our web services.
