### ISSUE TITLE
Should PartialEq impl compare language names?

### ISSUE THREAD

**Issue by couchand** [mike-engel/accept-language-rs#7]
It seems pretty suspicious that the impl of `PartialEq` for `Language` doesn't bother checking the language names.

**Comment by mike-engel** [comment]
@couchand do you have a test case that fails because of this?

**Comment by couchand** [comment]
Well, the test case here seems like a false positive as of #3: https://github.com/mike-engel/accept-language-rs/blob/27b987589f56c55cacc9590b200565c6f2451472/src/lib.rs#L149

**Comment by mike-engel** [comment]
@couchand If you'd like to write a PR, I'd be willing to review it. I'm not sure when I'll have time to work on this myself.

**Comment by mike-engel** [comment]
This has been fixed with 3.0.1
